openapi: 3.0.3
info:
  title: LexBot Backend API
  version: 0.1.0
paths:
  /upload:
    post:
      summary: Upload a document for indexing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id: { type: string }
  /search:
    get:
      summary: Search documents
      parameters:
        - in: query
          name: q
          schema: { type: string }
          required: true
        - in: query
          name: limit
          schema: { type: integer, default: 10, minimum: 1, maximum: 100 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total: { type: integer }
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        title: { type: string }
                        score: { type: number, format: float }